/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emulatoras;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 * Vytvorenie používateľského rozhrania.
 *
 * @author Tomi
 */
public class EmulatorFrame extends javax.swing.JFrame {

    private Analyza analyza;
    private Parser parser;
    private Save save;
    private InicializaciaPremennychFrame premenneFrame;
    private Boolean ulozenyText;
    private boolean inicializaciaStavov;

    /**
     * Zobrazí hlavné okno.
     */
    private void zobrazitOkno() {
        this.setEnabled(true);
    }

    /**
     * Vytvorenie okna s premennými.
     *
     * @param premenne
     */
    private void ukazPremenneFrame(List<String> premenne) {
        this.setEnabled(false);
        setInicializaciaStavov(false);
        premenneFrame = new InicializaciaPremennychFrame(premenne);
        premenneFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {  // definovanie operácii pri zatvoreni okna
                zobrazitOkno();
            }
        });
        premenneFrame.setVisible(true);
    }

    /**
     * Vytvorí nové okno pre Emulátora
     */
    public EmulatorFrame() {
        ulozenyText = true;
        initComponents();
        analyza = new Analyza();     //vlozeny kod
        save = new Save();
        viditelnostExportov(false);
        setInicializaciaStavov(false);

        this.addWindowListener(new WindowAdapter() {    // definovanie operácii pri zatvoreni okna
            @Override
            public void windowClosing(WindowEvent we) {
                if (ulozenyText == true) {
                    System.exit(0);
                } else {
                    ukoncenie();
                }
            }
        });
    }

    /**
     * Vyskakovacie okno pred ukončením programu.
     */
    public void ukoncenie() {
        jDialogExit.setLocationRelativeTo(null);
        jDialogExit.setVisible(true);
    }

    /**
     * Vymaže všetky polia pre výstup.
     *
     */
    public void vymaz() {
        if(premenneFrame != null){
        premenneFrame.setInicializovaneStavy(false);
        }
        viditelnostTlacidlaAnalyzy(false);
        premenne_pred.setListData(new String[0]);
        premenne_po.setListData(new String[0]);
        zasobnik_pred.setListData(new String[0]);
        zasobnik_po.setListData(new String[0]);
        instrukcie.setListData(new String[0]);
        stav_pred.setText("--");
        analyza.resetVsetky_premenne();
        stav_po.setText("--");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jDialogExit = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonľ = new javax.swing.JButton();
        btn_vykonaj = new javax.swing.JButton();
        btn_analyzuj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kod = new javax.swing.JTextArea();
        stavovyRiadok = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        instrukcie = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        btn_step_back = new javax.swing.JButton();
        btn_step_forward = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        zasobnik_pred = new javax.swing.JList();
        stav_pred = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        premenne_pred = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        zasobnik_po = new javax.swing.JList();
        stav_po = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        premenne_po = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jLabel1.setText("jLabel1");

        jDialogExit.setTitle("Ukončiť?");
        jDialogExit.setAlwaysOnTop(true);
        jDialogExit.setMinimumSize(new java.awt.Dimension(240, 120));
        jDialogExit.setModal(true);
        jDialogExit.setName("dialogExit"); // NOI18N
        jDialogExit.setResizable(false);

        jLabel10.setText("Projekt neuložený. Uložiť teraz ?");

        jButton1.setText("Ano");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_UkoncenieAno(evt);
            }
        });

        jButtonľ.setText("Nie");
        jButtonľ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_UkoncenieNie(evt);
            }
        });
        jButtonľ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonľActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogExitLayout = new javax.swing.GroupLayout(jDialogExit.getContentPane());
        jDialogExit.getContentPane().setLayout(jDialogExitLayout);
        jDialogExitLayout.setHorizontalGroup(
            jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogExitLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogExitLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonľ, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(43, 43, 43))
        );
        jDialogExitLayout.setVerticalGroup(
            jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonľ))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emulátor AS");
        setResizable(false);

        btn_vykonaj.setText("Vykonaj");
        btn_vykonaj.setEnabled(false);
        btn_vykonaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Vykonaj(evt);
            }
        });

        btn_analyzuj.setText("Analyzuj");
        btn_analyzuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analyzujAkcia(evt);
            }
        });

        jLabel2.setLabelFor(kod);
        jLabel2.setText("Vstupný kód");

        kod.setColumns(20);
        kod.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        kod.setRows(5);
        kod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zmenaKodu(evt);
            }
        });
        jScrollPane1.setViewportView(kod);

        stavovyRiadok.setForeground(new java.awt.Color(102, 102, 102));
        stavovyRiadok.setText("Pripravený");

        instrukcie.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        instrukcie.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                instrukcieValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(instrukcie);

        jLabel3.setText("Inštrukcie");

        btn_step_back.setText("<");
        btn_step_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_krokSpat(evt);
            }
        });

        btn_step_forward.setText(">");
        btn_step_forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_krokDopredu(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pred inštrukciou", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 0, 14))); // NOI18N

        jLabel4.setText("Stav");

        jLabel6.setLabelFor(zasobnik_pred);
        jLabel6.setText("Zásobník");

        zasobnik_pred.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(zasobnik_pred);

        stav_pred.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stav_pred.setText("--");

        premenne_pred.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(premenne_pred);

        jLabel9.setText("Premenné");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stav_pred)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(stav_pred))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Po inštrukcii", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 0, 14))); // NOI18N

        jLabel5.setText("Stav");

        jLabel7.setLabelFor(zasobnik_po);
        jLabel7.setText("Zásobník");

        zasobnik_po.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(zasobnik_po);

        stav_po.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stav_po.setText("--");

        premenne_po.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(premenne_po);

        jLabel8.setText("Premenné");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stav_po))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(stav_po))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        jMenu2.setText("Súbor");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nový");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Novy(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Novy2(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Otvoriť");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Open(evt);
            }
        });
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Open2(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Uložiť");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Uloz(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Uloz2(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Uložiť ako");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_UlozAko(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UlozAko2(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator3);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Exportovať");
        jMenuItem7.setToolTipText("");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Export(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Export po riadkoch");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportPoRiadkoch(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Ukončiť");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Ukoncenie(evt);
            }
        });
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ukoncenie2(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stavovyRiadok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_analyzuj)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_vykonaj)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_step_back)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_step_forward)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_analyzuj)
                    .addComponent(btn_vykonaj)
                    .addComponent(btn_step_back)
                    .addComponent(btn_step_forward))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stavovyRiadok)
                .addGap(6, 6, 6))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");
        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Vloží text do stavového riadku.
     *
     * @param text
     */
    private void setStavovyRiadok(String text) {
        stavovyRiadok.setText(text);
    }

    /**
     * Nastaví tlačidlo analýzy a vykonania.
     *
     * @param analyzed
     */
    private void viditelnostTlacidlaAnalyzy(boolean analyzed) {
        if (analyzed) {
            setStavovyRiadok("Analýza OK, stlačte Vykonaj pre vykonanie");
        }
        btn_vykonaj.setEnabled(analyzed);
        btn_analyzuj.setEnabled(!analyzed);
    }

    /**
     * Vyplní list inštrukciami.
     */
    private void vyplnitInstrukcie() {
        Vykonavanie v = Vykonavanie.getInstance();
        Krok[] kroky = new Krok[v.getKroky().size()];
        int i = 0;
        for (Krok k : v.getKroky()) {
            kroky[i++] = k;
        }
        instrukcie.setListData(kroky);
    }

    /**
     * Obnoví všetky polia patriace k inštrukcii potrebne pre výpis.
     */
    private void updateSelection() {
        int index = instrukcie.getSelectedIndex();
        if (index == -1) {
            return;
        }
        Vykonavanie v = Vykonavanie.getInstance();
        Krok k = v.getKroky().get(index);
        premenne_pred.setListData(k.getPremenne());
        zasobnik_pred.setListData(k.getZasobnik());
        stav_pred.setText("s" + (k.getStav()));
        if (isInicializaciaStavov()) {
            stav_pred.setText("s" + (k.getStav() - 1));
        }
        if (index < v.getKroky().size() - 1) {
            k = v.getKroky().get(index + 1);
        }
        premenne_po.setListData(k.getPremenne());
        zasobnik_po.setListData(k.getZasobnik());
        stav_po.setText("s" + (k.getStav()));

        if (isInicializaciaStavov()) {
            stav_po.setText("s" + (k.getStav() - 1));
        }
    }

    /**
     * Po stlačení ľubovoľného tlačidla sa mohol zmeniť vstupný kód a preto je
     * potrebná opätovná analýza.
     *
     * @param evt
     */
    private void zmenaKodu(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zmenaKodu
        viditelnostTlacidlaAnalyzy(false);
        ulozenyText = false;
        viditelnostExportov(false);
    //    premenneViditelnost.setEnabled(false);
    }//GEN-LAST:event_zmenaKodu

    private void instrukcieValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_instrukcieValueChanged
        updateSelection();
    }//GEN-LAST:event_instrukcieValueChanged
    /**
     * Tlačidlo nasledujúcej inštrukcie.
     *
     * @param evt
     */
    private void btn_krokSpat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_krokSpat
        int index = instrukcie.getSelectedIndex() - 1;
        if (index < 0) {
            index = 0;
        }
        instrukcie.setSelectedIndex(index);
    }//GEN-LAST:event_btn_krokSpat
    /**
     * Tlačidlo predchádzajúcej inštrukcie.
     *
     * @param evt
     */
    private void btn_krokDopredu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_krokDopredu
        int index = instrukcie.getSelectedIndex();

        if (index == -1) {
            index = 0;
        } else {
            index++;
        }
        instrukcie.setSelectedIndex(index);
    }//GEN-LAST:event_btn_krokDopredu
    /**
     * Tlačidlo pre uloženie vstupných inštrukcií.
     *
     * @param evt
     */
    private void btn_Uloz(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Uloz
       
    }//GEN-LAST:event_btn_Uloz
    /**
     * Tlačidlo pre uloženie vstupných inštrukcií s voľbou umiestnenia a nazvu.
     *
     * @param evt
     */
    private void btn_UlozAko(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UlozAko
       
    }//GEN-LAST:event_btn_UlozAko
    /**
     * Tlacidlo vykonania kódu.
     *
     * @param evt
     */
    private void btn_Vykonaj(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Vykonaj
        Vykonavanie v = Vykonavanie.getInstance();
        Stav.clear();
        Zasobnik z = Zasobnik.getZasobnik();
        z.vymaz();
        v.clear();
        if (analyza.getVsetky_premenne().size() > 0) {
            premenneFrame.iniciovanieStavu();
        }
        try {
            setInicializaciaStavov(premenneFrame.getInicializovaneStavy());
        } catch (NullPointerException e) {
            setInicializaciaStavov(false);
        }
        try {
            parser = new Parser();
            parser.setInicializaciaStavov(isInicializaciaStavov());
            parser.parse(kod.getText());
            parser.log("<KONIEC>");
            vyplnitInstrukcie();
            viditelnostTlacidlaAnalyzy(false);
            setStavovyRiadok("OK");
            viditelnostExportov(true);
        } catch (StavException ex) {
            setStavovyRiadok(ex.getMessage());
            vymaz();
        } catch (ZasobnikException ex) {
            setStavovyRiadok(ex.getMessage());
            viditelnostTlacidlaAnalyzy(false);
            vymaz();
        } catch (MyParserException ex) {
            setStavovyRiadok(ex.getMessage());
            viditelnostTlacidlaAnalyzy(false);
            vymaz();
        } catch (StackOverflowError ex) {
            setStavovyRiadok("Nekonečný cyklus");
            vymaz();
            viditelnostTlacidlaAnalyzy(false);
            viditelnostExportov(false);
        }
    }//GEN-LAST:event_btn_Vykonaj
    /**
     * Tlačidlo pre otvorenie súboru.
     *
     * @param evt
     */
    private void btn_Open(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Open
      
    }//GEN-LAST:event_btn_Open

    private void jButtonľActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonľActionPerformed
        // Tlacidlo nie pre exit okno
    }//GEN-LAST:event_jButtonľActionPerformed
    /**
     * Tlačidlo pre ukončenie programu.
     *
     * @param evt
     */
    private void btn_Ukoncenie(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ukoncenie
       
    }//GEN-LAST:event_btn_Ukoncenie
    /**
     * Tlačidlo pre potvrdenie ukončenia (ANO)
     *
     * @param evt
     */
    private void btn_UkoncenieAno(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UkoncenieAno
        String text = kod.getText();
        try {
            jDialogExit.setVisible(false);
            save.saveAs(text);
            ulozenyText = true;
            System.exit(0);
            setStavovyRiadok("Súbor uložený: " + save.getAdresa());
        } catch (FileNotFoundException ex) {
            setStavovyRiadok(ex.getMessage());
        } catch (IOException ex) {
            setStavovyRiadok(ex.getMessage());
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_btn_UkoncenieAno
    /**
     * Tlačidlo pre potvrdenie ukončenia (NIE)
     *
     * @param evt
     */
    private void btn_UkoncenieNie(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UkoncenieNie
        System.exit(0);
    }//GEN-LAST:event_btn_UkoncenieNie
    /**
     * Tlačidlo pre spustenie analýzy.
     *
     * @param evt
     */
    private void btn_analyzujAkcia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analyzujAkcia
        try {
            viditelnostExportov(false);
            vymaz();
            analyza.resetVsetky_premenne();
            analyza.iniciuj(kod.getText());
            if (analyza.getVsetky_premenne().size() > 0) {
                ukazPremenneFrame(analyza.getVsetky_premenne());
                setInicializaciaStavov(false);
            }
            viditelnostTlacidlaAnalyzy(true);
        } catch (MyParserException ex) {
            setStavovyRiadok(ex.getMessage());
            viditelnostTlacidlaAnalyzy(false);
        }
    }//GEN-LAST:event_btn_analyzujAkcia

    /**
     * Vytvorí nový projekt.
     *
     * @param evt
     */
    private void btn_Novy(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Novy
      
    }//GEN-LAST:event_btn_Novy

    /**
     * Tlačidlo pre exportovanie programu.
     *
     * @param evt
     */
    private void btn_Export(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Export
        Krok krok = new Krok();
        krok.setInicializovanyStavNula(inicializaciaStavov);
        try {
            Export export = new Export(kod.getText());
            export.ExportObycajny(isInicializaciaStavov());
            setStavovyRiadok("Súbor exportovaný: " + export.getAdresa());
       }catch (MyParserException ex){
            setStavovyRiadok(ex.getMessage());
        } catch (IOException | NullPointerException |StringIndexOutOfBoundsException ex) {
            setStavovyRiadok("Neplatný export");
        }
    }//GEN-LAST:event_btn_Export

    private void btn_Novy2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Novy2
         viditelnostExportov(false);
        kod.setText("");
        vymaz();
    }//GEN-LAST:event_btn_Novy2

    private void btn_Open2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Open2
     try {
            viditelnostExportov(false);
            Open open = new Open();
            kod.setText(open.getKod());
            save.setAdresa(open.getAdresa());
            setStavovyRiadok("Súbor uložený: " + save.getAdresa());
            viditelnostTlacidlaAnalyzy(false);
            vymaz();
        } catch (FileNotFoundException ex) {
            setStavovyRiadok(ex.getMessage());
        } catch (IOException ex) {
            setStavovyRiadok(ex.getMessage());
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_btn_Open2

    private void btn_Uloz2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Uloz2
         String text = kod.getText();
        try {
            save.save(text);
            ulozenyText = true;
            setStavovyRiadok("Súbor uložený: " + save.getAdresa());
        } catch (FileNotFoundException ex) {
            setStavovyRiadok(ex.getMessage());
        } catch (IOException ex) {
            setStavovyRiadok(ex.getMessage());
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_btn_Uloz2

    private void btn_UlozAko2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UlozAko2
        String text = kod.getText();
        try {
            save.saveAs(text);
            ulozenyText = true;
            setStavovyRiadok("Súbor uložený: " + save.getAdresa());
        } catch (FileNotFoundException ex) {
            setStavovyRiadok(ex.getMessage());
        } catch (IOException ex) {
            setStavovyRiadok(ex.getMessage());
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_btn_UlozAko2

    private void btn_Ukoncenie2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ukoncenie2
       if (ulozenyText == false) {
            ukoncenie();
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_Ukoncenie2

    private void btn_ExportPoRiadkoch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportPoRiadkoch
        Krok krok = new Krok();
        krok.setInicializovanyStavNula(inicializaciaStavov);
        try {
            Export export = new Export(kod.getText());
            export.ExportPoRiadkoch(isInicializaciaStavov());
            setStavovyRiadok("Súbor exportovaný: " + export.getAdresa());
        }catch (MyParserException ex){
            setStavovyRiadok(ex.getMessage());
        } catch (IOException | NullPointerException |StringIndexOutOfBoundsException ex) {
            setStavovyRiadok("Neplatný export ");
        }
    }//GEN-LAST:event_btn_ExportPoRiadkoch

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set System L&F
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmulatorFrame emulatorFrame = new EmulatorFrame();
                emulatorFrame.setVisible(true);
                emulatorFrame.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_analyzuj;
    private javax.swing.JButton btn_step_back;
    private javax.swing.JButton btn_step_forward;
    private javax.swing.JButton btn_vykonaj;
    private javax.swing.JList instrukcie;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonľ;
    private javax.swing.JDialog jDialogExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextArea kod;
    private javax.swing.JList premenne_po;
    private javax.swing.JList premenne_pred;
    private javax.swing.JLabel stav_po;
    private javax.swing.JLabel stav_pred;
    private javax.swing.JLabel stavovyRiadok;
    private javax.swing.JList zasobnik_po;
    private javax.swing.JList zasobnik_pred;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the inicializaciaStavov
     */
    public boolean isInicializaciaStavov() {
        return inicializaciaStavov;
    }

    /**
     * @param inicializaciaStavov the inicializaciaStavov to set
     */
    public void setInicializaciaStavov(boolean inicializaciaStavov) {
        this.inicializaciaStavov = inicializaciaStavov;
    }
    
    private void viditelnostExportov( boolean viditelnost){
    jMenuItem7.setEnabled(viditelnost);
    jMenuItem2.setEnabled(viditelnost);
    
    }
}
